@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault

package net.ommina.wallpapercraftslabs.network;

import mcp.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;